### PR TITLE
Show Menu and Dock Icon whilst interacting

### LINKED ISSUE #83: Hide status bar icons after 10 seconds sometimes does not work
I'm on macos 10.15.1 (19B88),  dozer on 4.0.0, hide status bar icons after 10 seconds sometimes does not work.

### LINKED ISSUE #111: Some icons not accessible when using an app with many menus and/or narrow screen
# Problem
1. Use an app with many menus, eg. Safari
2. Have a load of menu icons and/or use a narrow screen
3. Try to access the left most icon

# Expected
- should be able to access all icons

# Actual
- cannot access some icons

Screen shot 2020-04-19 at 18 46 17

# Workaround
- sometimes you can switch to an app with fewer menus, eg. Finder

Screen shot 2020-04-19 at 18 46 28

- but even then some are unavailable

Screen shot 2020-04-19 at 18 46 41

- an app with one menu will let me get at them all

Screen shot 2020-04-19 at 18 49 35

# Extras 
- here's an app with one small menu item https://github.com/Mortennn/Dozer/issues/111#issuecomment-653469183
- here's a Dozer app with dock icon and one small menu item https://github.com/Mortennn/Dozer/issues/111#issuecomment-653750135

# Suggestion

- Make Dozer show it's own menu in certain circumstances

### LINKED ISSUE #115: 'Hide status bar icons after 10 seconds' not working; Dot disappears at times on menu bar
'Hide status bar icons after 10 seconds' is checked, but seems to not be working. Also, I've noticed when not in use and icons are hidden, the main dot seems to disappear at times.

Screen Shot 2020-06-15 at 7 43 29 PM

V 4.0.0
Mac OS High Sierra 
10.13.6

### LINKED ISSUE #120: Should refer to Menu Bar Extras, not Status Bar Icons
Currently the app refers to the things it hides as "Status Bar Icons" but in fact they are called "Menu Bar Extras". A compromise would be to call them "Menu Bar Icons".

> **Menu Bar Extras**
A menu bar extra exposes app-specific functionality via an icon that appears in the menu bar when your app is running, even when it’s not the frontmost app. Menu bar extras are on the opposite side of the menu bar from your app's menus. The system hides menu bar extras to make room for app menus. Similarly, if there are too many menu bar extras, the system may hide some to avoid crowding app menus.

https://developer.apple.com/design/human-interface-guidelines/macos/extensions/menu-bar-extras

> Screen shot 2020-07-04 at 11 14 08

### LINKED ISSUE #123: Allow Cmd+Q to quit app when preference window is visible
## Expected
- <kbd>Cmd</kbd>+<kbd>Q</kbd> should quit app when preference window is visible

## Actual
- Has no effect

## Fix
In #121 I have assigned a shortcut key to the Quit button, so the window can be quit as long as the pane with the Quit button is visible.

### LINKED ISSUE #125: One too many start timers being fired when showing icons
This is an issue so I can mark it as solved.

I put debug logging at the start of every method and watched the flow.

> These are from my personal config, yours may differ.
## Init

- "Dozer: init"
- "Dozer: showAll"
- "Dozer: didShowStatusBarIcons"
- "Dozer: startTimer"
- "Dozer: startUserInteractionTimer"
- "Dozer: hide"
- "Dozer: didHideStatusBarIcons"
- "Dozer: stopTimer"
- "Dozer: stopUserInteractionTimer"
- "Dozer: hideIconAndMenu"
- "Dozer: toggleDockIcon"
- "Dozer: toggleDockIcon"

## Showing icons

- "Dozer: toggle"
- "Dozer: show"
- "Dozer: resetTimer"
- "Dozer: stopTimer"
- "Dozer: startTimer"
- "Dozer: didShowStatusBarIcons"
- **"Dozer: startTimer"**
- "Dozer: startUserInteractionTimer"
- "Dozer: showIconAndMenu"
- "Dozer: toggleDockIcon"

## Hiding icons

- "Dozer: toggle"
- "Dozer: hide"
- "Dozer: didHideStatusBarIcons"
- "Dozer: stopTimer"
- "Dozer: stopUserInteractionTimer"
- "Dozer: hideIconAndMenu"
- "Dozer: toggleDockIcon"

As we can see, there is a double call to `startTimer` when Showing icons. 

## Bug

If you repeatedly click the dozer icon to show/hide menu bar icons, try it every one second frequency, then at some point you will be interrupted by the stray timers ending and hiding the icons.

## Fix

Remove stray startTimer call, see #121

### PR DESCRIPTION
**Pull request by gingerbeardman**
> Please give a small summary of what has changed. 

- Adds support for showing Dozer Menu and Dock Icon whilst interacting with Dozer. Fixes #111 
  - Controlled by new user preference, default is Off
- Changes "status bar" references to "menu bar". Fixes #120
- Moves timer reset in option-click code path. Possibly Fixes #83, Fixes #115
- UI tweaks to tidy up alignments and spacing on prefs panel
- Cmd+Q to quit when "Dozer" preferences panel with quit button is visible, Fixes #123 
- Remove superfluous `startTimer` call, Fixes #125

### CODE REVIEW

File: Dozer/DozerIcons.swift [hunk 1]
```diff
@@ -255,9 +278,20 @@ public final class DozerIcons {
         }
     }
 
-    /// Determines if the user is interacting with the status bar based on level, owner and y-coordinate
+    /// hide and show dock icon and thus its menu bar
```
Comment (decadent) [inline Dozer/DozerIcons.swift:281]: Personally I would put in *why* the function does that, i.e. “so the menu bar is freed up and all icons are visible”.

Comment (gingerbeardman) [reply Dozer/DozerIcons.swift]: have done so! cheers

File: Dozer/DozerIcons.swift [hunk 2]
```diff
@@ -86,6 +86,12 @@ public final class DozerIcons {
         }
     }
 
+    public var enableIconAndMenu: Bool = Defaults[.showIconAndMenuEnabled] {
+        didSet {
+            Defaults[.showIconAndMenuEnabled] = self.enableIconAndMenu
```
Comment (Mortennn) [inline Dozer/DozerIcons.swift:91]: When unchecking "Show Dozer menu and dock icon whilst interacting" then dock icon does not disappear. Only when restarting Dozer. The following would fix that. 
```suggestion
            Defaults[.showIconAndMenuEnabled] = self.enableIconAndMenu
            if self.enableIconAndMenu == false {
                _ = DozerIcons.toggleDockIcon(showIcon: false)
                appDelegate.preferencesWindowController.show(preferencePane: .general)
            }
```
What do you think about showing the preferences window again? It gliches shortly, but it may be better than it just disappearing.

**Comment by Mortennn** [comment]
Great feature and PR!😀

File: Dozer/DozerIcons.swift (hunk 2 above)
Comment (gingerbeardman) [reply Dozer/DozerIcons.swift:91]: Glad you like it! It's been a pleasure to do this PR. 

I'll implement the fix. 

I'm not sure what the preference window issue is?

**Comment by gingerbeardman** [comment]
I'll look into this and fix it

**Comment by gingerbeardman** [comment]
@Mortennn I think that's fixed! I just set dock icon hidden on launch.

File: Dozer/DozerIcons.swift (hunk 2 above)
Comment (Mortennn) [reply Dozer/DozerIcons.swift:91]: Nevermind about the issue about the preference window. No problem there.

**Comment by Mortennn** [comment]
@gingerbeardman That fixes it - nice work! I still experience one last issue with the feature: When the Dozer icon is hidden and you enable the feature, when you then click the Dozer icon to show the menu bar icons, the feature does nothing. However, the feature works after you toggle the dozer icon twice.

**Comment by gingerbeardman** [comment]
Ah, I thought I had fixed that one. I'll take another look!

**Comment by Mortennn** [comment]
Ignore the merge conflict. I will accept you change when the PR is merged.

**Comment by gingerbeardman** [comment]
@Mortennn I can no longer reproduce the problem, I could at once point and believe it was solved in https://github.com/Mortennn/Dozer/pull/121/commits/513118525f63e840b9e71968daacd7254cec03e0

Can you please confirm?

File: Dozer/DozerIcons.swift [hunk 3]
```diff
@@ -139,7 +153,27 @@ public final class DozerIcons {
         }
     }
 
-    /// Force show all Dozer status bar icons
+    public func showIconAndMenu() {
+        if NSWorkspace.shared.frontmostApplication?.bundleIdentifier != "com.mortennn.Dozer" {
```
Comment (decadent) [inline Dozer/DozerIcons.swift:157]: As a nitpick: I wouldn't hardcode this. [It seems there's a constant for it](https://github.com/Mortennn/Dozer/blob/9705af61301c90b4d91928a957378d9d30c8b295/Dozer/Constants.swift#L37), though personally I'm surprised if the build process or the runtime don't supply it from Info.plist.

Comment (gingerbeardman) [reply Dozer/DozerIcons.swift:157]: Good spot!

File: Dozer/DozerIcons.swift [hunk 4]
```diff
@@ -255,9 +289,20 @@ public final class DozerIcons {
...
-    /// Determines if the user is interacting with the status bar based on level, owner and y-coordinate
+    /// hide and show dock icon and thus its menu bar: to free up space to show more menu bar icons
+    public class func toggleDockIcon(showIcon state: Bool) -> Bool {
+        var result: Bool
+        if state {
+            result = NSApp.setActivationPolicy(NSApplication.ActivationPolicy.regular)
+        } else {
+            result = NSApp.setActivationPolicy(NSApplication.ActivationPolicy.accessory)
+        }
+        return result
```
Comment (decadent) [inline Dozer/DozerIcons.swift:300]: I'll keep shuddering a little knowing that some code running on my machine is so devoted to not having early returns.

Comment (gingerbeardman) [reply Dozer/DozerIcons.swift:300]: Feel free to suggest a change

Comment (decadent) [reply Dozer/DozerIcons.swift:300]: Well, in this case I'd write it in one line:

`return NSApp.setActivationPolicy(state ? NSApplication.ActivationPolicy.regular : NSApplication.ActivationPolicy.accessory)`

Dunno if Swift's `[.thing]` syntax allows to remove the duplication of `NSApplication.ActivationPolicy` too.

Generally, I'm a big fan of early `return`s, especially for exceptional inputs that cause functions to not do usual stuff. They're pretty much saying “input wrong? no can do” right at the start, and as a bonus avoid extra nesting. Also they work smoothly with more-functional style, which is very nice, in my book.

**Comment by Mortennn** [comment]
> @Mortennn I can no longer reproduce the problem of "having to click the Dozer icon twice"
> 
> I could when you mentioned it, on 5 July, and believe it was solved in [5131185](https://github.com/Mortennn/Dozer/commit/513118525f63e840b9e71968daacd7254cec03e0)
> 
> Can you please confirm?

@gingerbeardman Yes, I can't reproduce either.

File: Dozer/DozerIcons.swift (hunk 4 above)
Comment (gingerbeardman) [reply Dozer/DozerIcons.swift:300]: Swift warning
> Implicit Return Violation: Prefer implicit returns in closures, functions and getters. (implicit_return)

**Comment by gingerbeardman** [comment]
Then I'm happy for this to be merged.

I'm sure the coe will continue to change in time.

**Comment by Mortennn** [comment]
@gingerbeardman Yes, let's do it. Thank you for your work🙌

File: Dozer/DozerIcons.swift (hunk 4 above)
Comment (decadent) [reply Dozer/DozerIcons.swift:300]: Ah, apparently it's Swift [saying to drop `return` altogether in one-liner functions](https://github.com/apple/swift-evolution/blob/master/proposals/0255-omit-return.md). Didn't know about that. Seems they're bent even further in the functional direction than older mainstream languages.

**Comment by gingerbeardman** [comment]
My pleasure. It was much fun!

**Comment by aonez** [comment]
Thanks @gingerbeardman! 🎉

**Comment by gingerbeardman** [comment]
How's it going with this @Mortennn ?

**Comment by Mortennn** [comment]
@gingerbeardman I have published a prerelease of 4.2.0, because I have an issue about notarizing Dozer, which I have contacted Apple about. Also, I am away for a week, so I will release it when I am back and able to fix any issues when people are updating.

**Comment by gingerbeardman** [comment]
How are things going @Mortennn ?

**Comment by aonez** [comment]
@Mortennn If you still have issues about notarization share it here, maybe we can help :)
